name: Next Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /services/Laravel-ReactJS-Inventory_Management_System
            git fetch origin
            git checkout main
            git pull
            sudo docker rm -f ims-service || true
            sudo docker image rm ims-service || true
            sudo docker build -t ims-service .
            sudo docker run -d --name ims-service -p 8080:80 ims-service
